---
title: "Model"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Train test split

```{r package}
library(DT)
library(data.table)
library(caret) #this package has the createDataPartition function
```

```{r load_data}
set.seed(10)
dt <- fread( input = "../Data/pruned_green_cab.csv")

```

dt[,.(pick_up = get(lpep_pickup_datetime))]
### drop unnecessary column
```{r transform date}
dt$store_and_fwd_flag <- NULL
dt$VendorID <- NULL

# Monday is 1, Sunday is 0.
dt$weekday <- dt$pickup_hour %% (24*7)

# hourly density
dt$demand <- dt$pickup_hour 

final_dt <- merge(dt, dt[,.N, by = pickup_hour])
```

```{r feature_selection}
names(final_dt)
selected_dt <- final_dt[, c("pickup_hour","dropoff_hour","RatecodeID","PULocationID","DOLocationID","passenger_count","trip_distance","extra","mta_tax","tolls_amount","improvement_surcharge", "payment_type","trip_type","weekday","fare_amount","tip_amount","N" ) ]
```

```{r train test split}
#creating indices
trainIndex <- createDataPartition(selected_dt[1:10000,]$N,p=0.75,list=FALSE)
#splitting data into training/testing data using the trainIndex object
cab_TRAIN <- selected_dt[trainIndex,] #training data (75% of data) 
cab_TEST <- selected_dt[-trainIndex,] #testing data (25% of data)
names(cab_TRAIN)
```

### target is fare_amount tip_amount demand(N)

```{r load model library echo = FALSE}
library(data.table)
library(DT)
library(dplyr)
library(nnet)
library(class)
library(rpart)
library(FNN)
library(randomForest)
library(glmnet)
library(e1071)
library(gbm)
library(xgboost)
library(MASS)
library(klaR)
library(caret)
```

```{r linear_model}
model_glm <- glmnet(x = as.matrix(cab_TRAIN[,-c(15,16,17)]),
                y = as.matrix(cab_TRAIN[,c(17)]),
                alpha = 1,
                family = "gaussian")


prediction <- predict(object = model_glm,
                      newx = as.matrix(cab_TEST[,-c(15,16,17)]),
                      type = "link")
```

```{r knn_r}
model_knn <- knn.reg(cab_TRAIN, test = NULL, y, k = 3, algorithm=c("kd_tree", 
        "cover_tree", "brute"))

model_knn.reg <- knn.reg(train = cab_TRAIN[,-c(15,16,17)],
                      test = cab_TEST[,-c(17)],
                      cl = cab_TRAIN[,c(15,16,17)],
                      k = K)
``






