---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r set_up}
library(DT)
library("data.table")
library(lubridate)
```

```{r load_data}
green_cab <- fread(input = "../Data/2018_Green_Taxi_Trip_Data.csv")
```

```{r load_table}
taxi_zone <- fread(input = "../Data/taxi+_zone_lookup.csv")
```

Data Exploration
```{r head}
head(green_cab)
```

```{r exploration}
sapply(green_cab, class)
```

Data cleaning

VendorID
```{r data_cleaning_VendorID}
pruned_green_cab <- green_cab[VendorID %in% c(1,2),]
```

PULocationID_DOLocationID
```{r data_cleaning_PULocationID_DOLocationID}
#PULocationID_DOLocationID only 1-265

quantile(green_cab$PULocationID, probs = c(0, 0.005, 0.025, 0.5, 0.75, 0.975, 0.995, 1))
quantile(green_cab$DOLocationID, probs = c(0, 0.005, 0.025, 0.5, 0.75, 0.975, 0.995, 1))
pruned_green_cab <- pruned_green_cab[PULocationID>0&PULocationID<266&DOLocationID>0&DOLocationID<266,]
```

Passenger_count
```{r data_cleaning_Passenger_count}
quantile(green_cab$passenger_count, probs = c(0, 0.005, 0.025, 0.5, 0.75, 0.975, 0.995, 1))

pruned_green_cab <- pruned_green_cab[passenger_count > 0 & passenger_count < 6,]
```


trip_distance
```{r data_cleaning_trip_distance}
quantile(green_cab$trip_distance, probs = c(0, 0.005, 0.025, 0.5, 0.75, 0.975, 0.995, 1))

pruned_green_cab <- pruned_green_cab[trip_distance >= 0 & trip_distance <22,]
```

fare_amount
```{r data_cleaning_fare_amount}
quantile(green_cab$fare_amount, probs = c(0, 0.005, 0.025, 0.5, 0.75, 0.975, 0.995, 1))

pruned_green_cab <- pruned_green_cab[fare_amount >= 2.5 & fare_amount <= 46.5,]
```

extra
```{r data_cleaning_extra}
quantile(green_cab$extra, probs = c(0, 0.005, 0.025, 0.5, 0.75, 0.975, 0.995, 1))

pruned_green_cab <- pruned_green_cab[extra >= 0 & extra <= 1,]
```

mta_tax
```{r data_cleaning_mta_tax}
quantile(green_cab$mta_tax, probs = c(0, 0.005, 0.025, 0.5, 0.75, 0.975, 0.995, 1))

pruned_green_cab <- pruned_green_cab[mta_tax > 0 & mta_tax <= 0.5,]
```

tip_amount
```{r data_cleaning_tip_amount}
quantile(green_cab$tip_amount, probs = c(0, 0.005, 0.025, 0.5, 0.75, 0.975, 0.995, 1))

pruned_green_cab <- pruned_green_cab[tip_amount >= 0 & tip_amount <= 0.5,]
```

tolls_amount
```{r data_cleaning_tolls_amount}
quantile(green_cab$tolls_amount, probs = c(0, 0.005, 0.025, 0.5, 0.75, 0.975, 0.995, 1))

pruned_green_cab <- pruned_green_cab[tolls_amount >= 0 & tolls_amount <= 5.76,]
```

ehail_fee
```{r data_cleaning_ehail_fee}
#all NA remove itï¼

pruned_green_cab$ehail_fee <- NULL
```

improvement_surcharge
```{r data_cleaning_improvement_surcharge}
quantile(green_cab$improvement_surcharge, probs = c(0, 0.005, 0.025, 0.5, 0.75, 0.975, 0.995, 1))

pruned_green_cab <- pruned_green_cab[improvement_surcharge == 0.3, ]
```

total_amount
```{r data_cleaning_total_amount}
quantile(green_cab$total_amount, probs = c(0, 0.005, 0.025, 0.5, 0.75, 0.975, 0.995, 1))

pruned_green_cab <- pruned_green_cab[total_amount >= 3.3 & total_amount <= 73.32,]
```

payment_type
```{r data_cleaning_payment_type}
#only 1 -6  others do not make sense
summary(green_cab$payment_type)

pruned_green_cab <- pruned_green_cab[payment_type %in% c(1,2,3,4,5,6),]
```

trip_type
```{r data_cleaning_trip_type}
#only 1 or 2  others do not make sense
summary(green_cab$trip_type)

pruned_green_cab <- pruned_green_cab[trip_type %in% c(1,2),]
```

lpep_pickup_datetime lpep_dropoff_datetime
```{r data_cleaning_lpep_pickup_datetime_lpep_dropoff_datetime}


one.year <- (as.numeric(strptime("01/01/2019 12:00:00 AM", "%m/%d/%Y %l:%M:%S %p")) - as.numeric(strptime("01/01/2018 12:00:00 AM", "%m/%d/%Y %l:%M:%S %p"))) %/% 3600

pruned_green_cab$pickup_hour <- 
  (as.numeric(strptime(pruned_green_cab$lpep_pickup_datetime, "%m/%d/%Y %l:%M:%S %p")) - as.numeric(strptime("01/01/2018 12:00:00 AM", "%m/%d/%Y %l:%M:%S %p"))) %/% 3600

pruned_green_cab$dropoff_hour <- (as.numeric(strptime(pruned_green_cab$lpep_dropoff_datetime, "%m/%d/%Y %l:%M:%S %p")) - as.numeric(strptime("01/01/2018 12:00:00 AM", "%m/%d/%Y %l:%M:%S %p"))) %/% 3600

pruned_green_cab$trip_duration <- 
  ((as.numeric(strptime(pruned_green_cab$lpep_dropoff_datetime, "%m/%d/%Y %l:%M:%S %p")) - as.numeric(strptime("01/01/2018 12:00:00 AM", "%m/%d/%Y %l:%M:%S %p")))
- 
  (as.numeric(strptime(pruned_green_cab$lpep_pickup_datetime, "%m/%d/%Y %l:%M:%S %p")) - as.numeric(strptime("01/01/2018 12:00:00 AM", "%m/%d/%Y %l:%M:%S %p")))) /60


pruned_green_cab <- pruned_green_cab[pickup_hour>=0 & pickup_hour<=one.year,]

pruned_green_cab <- pruned_green_cab[dropoff_hour>=0 & dropoff_hour<=one.year,]

pruned_green_cab <- pruned_green_cab[trip_duration>=1.866667 & trip_duration<=46.400000,]

quantile(pruned_green_cab$pickup_hour, probs = c(0, 0.005, 0.025, 0.5, 0.75, 0.975, 0.995, 1))
quantile(pruned_green_cab$dropoff_hour, probs = c(0, 0.005, 0.025, 0.5, 0.75, 0.975, 0.995, 1))
quantile(pruned_green_cab$trip_duration, probs = c(0, 0.005, 0.025, 0.5, 0.75, 0.975, 0.995, 1))
```


### feature engineering

```{r add_weather_data}
weather_dt <- fread(input = "../Data/weather_new.csv")
weather_dt$DATE <- NULL

a <- merge(x = pruned_green_cab, y = weather_dt, by.x = "pickup_hour", by.y = "HOUR")

# Monday is 1, Sunday is 0.
a$weekday <- a$pickup_hour %% (24*7)

a[, "N" := .N, by = c("pickup_hour", "PULocationID")]

a[, "TotalRevenue" := sum(total_amount), by = c("pickup_hour", "PULocationID")]

a[, "AvgRevenue" := TotalRevenue/N, by = c("pickup_hour", "PULocationID")]

# pruned_green_cab <- fread(input = "../Data/pruned_green_cab.csv")
```

### drop unnecessary column
```{r transform date}
names(a)
a$store_and_fwd_flag <- NULL
a$VendorID <- NULL
a$lpep_pickup_datetime <- NULL
a$lpep_dropoff_datetime <- NULL

names(a) <- c("PickupHour", "RatecodeID", "PULocationID", "DOLocationID", "PassengerCount", "TripDistance", "FareAmount", "Extra", "MtaTax", "TipAmount", "TollsAmount", "ImprovementSurcharge", "TotalAmount", "PaymentType", "TripType", "DropoffHour", "TripDuration", "HourlyDewPointTemperature","HourlyPrecipitation", "HourlyWindSpeed", "Weekday", "N", "TotalRevenue", "AvgRevenue" )
```


```{r output_pruned_dataset}
write.csv(a, file = "../Data/pruned_green_cab.csv",row.names=FALSE, na="")
```
